Use foreman 1.15 (#13)
* Use 1.15 while "latest" (1.16) repo dependency version conflict exists.

```
Error: Package: tfm-rubygem-runcible-1.12.0-1.el7.noarch (katello)
           Requires: tfm-rubygem(rest-client) < 2.0.0
           Installing: tfm-rubygem-rest-client-2.0.1-1.el7.noarch (foreman)
               tfm-rubygem(rest-client) = 2.0.1
```